export const CELL_SIZE = 4;
export const WALL_HEIGHT = 3;
export const WALL_THICKNESS = 0.2;
export const EYE_HEIGHT = 1.6;
export const PLAYER_RADIUS = 0.3;
export const MOVE_SPEED = CELL_SIZE * 1.2; // world units / second
export const TURN_SPEED = 2.5; // radians / second
export const MAZE_WIDTH = 30;
export const MAZE_HEIGHT = 30;
